### ISSUE TITLE
Want CPU processor information

### ISSUE THREAD

**Issue by bdha** [joyent/hwgrok#1]
Currently the processors object is mostly empty:

```
  "processors": [
    {
      "number-of-threads-per-core": 2,
      "number-of-cores": 14,
      "model": "unknown",
      "label": "(null)",
      "leds": [],
      "manufacturer": "unknown",
      "sensors": []
    },
    {
      "sensors": [],
      "manufacturer": "unknown",
      "leds": [],
      "label": "(null)",
      "model": "unknown",
      "number-of-threads-per-core": 2,
      "number-of-cores": 14
}
```

This information is available on the system, though maybe only by reading `smbios -t 4`?

Conch uses this information to validate that the system has the appropriate number and make of CPUs.

**Comment by rejohnst** [comment]
hwgrok can expose some additional bits from the chip topo node - see below for what's currently available.  What isn't there is a brand string, which is tracked by OS-7150

[root@smartos-home /var/tmp]# /usr/lib/fm/fmd/fmtopo -P chip-properties "*chip=0"
TIME                 UUID
Aug 20 19:06:20 ea85bddf-5817-c478-b944-edc2e9b13d9e

hc://:product-id=System-Product-Name:server-id=smartos-home:chassis-id=System-Serial-Number/motherboard=0/chip=0
  group: chip-properties                version: 1   stability: Private/Private
    vendor_id         string    GenuineIntel
    family            int32     6
    model             int32     158
    stepping          int32     9

**Comment by rejohnst** [comment]
My latest push also now includes the processor brand string - (see example below).  It's dependent on the changes for OS-7150, which are in code review now and should integrate into illumos-joyent tomorrow.

[
  {
    "label": "unknown",
    "hc-fmri": "hc:///motherboard=0/chip=0",
    "manufacturer": "Intel",
    "model": "unknown",
    "processor-brand": "Intel(r) Xeon(r) Gold 6132 CPU @ 2.60GHz",
    "processor-family": "6",
    "processor-model": "85",
    "processor-stepping": "4",
    "number-of-cores": 14,
    "number-of-threads-per-core": 2,
    "sensors": [],
    "leds": []
  },
  {
    "label": "unknown",
    "hc-fmri": "hc:///motherboard=0/chip=1",
    "manufacturer": "Intel",
    "model": "unknown",
    "processor-brand": "Intel(r) Xeon(r) Gold 6132 CPU @ 2.60GHz",
    "processor-family": "6",
    "processor-model": "85",
    "processor-stepping": "4",
    "number-of-cores": 14,
    "number-of-threads-per-core": 2,
    "sensors": [],
    "leds": []
  }
]
